default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5 
  username: postgres
  password: qwerty
  database: multiwoven_server_development

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %> 
  pool: 5 
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: multiwoven_server_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5 
  username: postgres 
  password: qwerty
  database: multiwoven_server_production
